version: '3.7'
volumes:
  pg-data:

services:
  web:
    build:
      context: .
    volumes:
      - ./:/workdir/
    command: "python3 run_web.py"
    restart: always
    ports:
      - "${API_PORT}:6600"